title: 山河
baseurl: "/photos"
url: "https://mikewei.github.io"

# Build settings
markdown: kramdown
# plugins:
#   - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - album/

# 添加以下行
include: []
